<?php

namespace Proxies\__CG__\Synapse\Cmf\Bundle\Entity\Orm;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Component extends \Synapse\Cmf\Bundle\Entity\Orm\Component implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'componentTypeId', '' . "\0" . 'Synapse\\Cmf\\Bundle\\Entity\\Orm\\Component' . "\0" . 'zone', 'id', 'componentType', 'data', 'ranking', 'createdAt', 'updatedAt', '' . "\0" . 'Synapse\\Cmf\\Bundle\\Entity\\Orm\\Component' . "\0" . 'delegatesCollection'];
        }

        return ['__isInitialized__', 'componentTypeId', '' . "\0" . 'Synapse\\Cmf\\Bundle\\Entity\\Orm\\Component' . "\0" . 'zone', 'id', 'componentType', 'data', 'ranking', 'createdAt', 'updatedAt', '' . "\0" . 'Synapse\\Cmf\\Bundle\\Entity\\Orm\\Component' . "\0" . 'delegatesCollection'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Component $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getComponentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentId', []);

        return parent::getComponentId();
    }

    /**
     * {@inheritDoc}
     */
    public function getComponentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentType', []);

        return parent::getComponentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setComponentType(\Synapse\Cmf\Framework\Theme\ComponentType\Model\ComponentTypeInterface $componentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComponentType', [$componentType]);

        return parent::setComponentType($componentType);
    }

    /**
     * {@inheritDoc}
     */
    public function setZone(\Synapse\Cmf\Bundle\Entity\Orm\Zone $zone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZone', [$zone]);

        return parent::setZone($zone);
    }

    /**
     * {@inheritDoc}
     */
    public function getComponentTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentTypeId', []);

        return parent::getComponentTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getData($key = NULL, $default = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', [$key, $default]);

        return parent::getData($key, $default);
    }

    /**
     * {@inheritDoc}
     */
    public function setData(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getRanking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRanking', []);

        return parent::getRanking();
    }

    /**
     * {@inheritDoc}
     */
    public function setRanking($ranking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRanking', [$ranking]);

        return parent::setRanking($ranking);
    }

    /**
     * {@inheritDoc}
     */
    public function normalize($scope = 'default')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'normalize', [$scope]);

        return parent::normalize($scope);
    }

    /**
     * {@inheritDoc}
     */
    public function denormalize(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'denormalize', [$data]);

        return parent::denormalize($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt($format = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', [$format]);

        return parent::getCreatedAt($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt($format = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', [$format]);

        return parent::getUpdatedAt($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function registerLoader($field, \Closure $delegate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registerLoader', [$field, $delegate]);

        return parent::registerLoader($field, $delegate);
    }

    /**
     * {@inheritDoc}
     */
    public function registerLoaders(array $loaders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registerLoaders', [$loaders]);

        return parent::registerLoaders($loaders);
    }

}
